### ISSUE TITLE
Necessary changes to migrate the test sample to django 2.x.x

### ISSUE THREAD

**Issue by xdanielsb** [nephila/django-knocker#13]
**1. In the file /tests/example_app/models.py replace " django.core.urlresolvers import reverse " to " from django.urls import reverse "
2. in the file /tests/example_app/models.py in the attribute author add the attribute on_delete with the value that fits better for you.
3. in /tests/example_app/urls.py   the views  javascript_catalog  and json_catalog view were removed 
4. remove the include method in admin.site.urls it is not necesary in the new version.**

**Comment by yakky** [comment]
@xdanielsb thanks
we completely overhauled this package for channels 2 and we fixed with #15
