### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by koopauy** [nephila/django-knocker#5]
Great option to notify all connected users!

I'm trying to implement it, but i can't notify yet, the actual documentation it's very poor and i couldn't find any tutorial.

**Comment by yakky** [comment]
is this link https://www.nephila.it/talk/channels-drf.html of any help?
You can also refer to https://github.com/nephila/djangocms-blog which is the reference implementation
My plan is to push a sample application + simple project to test it

**Comment by koopauy** [comment]
I've been testing and i finally could send notifications, but in the model y use this:

@receiver(post_save, sender=Notification)
def notify(sender, instance, **kwargs):
    instance.send_knock(True)

**Comment by yakky** [comment]
@koopauy that's strange. Signal should be connected whenever the model is instantiated. What was your issue which was not addressed in the documentation? I want to track documentation improvement in #6
and your feedback would be very helpful

**Comment by koopauy** [comment]
Hi @yakky i've uploaded the test project to https://github.com/koopauy/channels_test you can check there.
Actually i can send desktop notifications with that signal that i post before.
Regards.
