### ISSUE TITLE
Signal Not Firing on Model Create / Update

### ISSUE THREAD

**Issue by aubricus** [nephila/django-knocker#8]
Thanks for taking the time to help:

__Issue:__

Models do not send knock when they are created or updated.

I threw a `pbd` into `knocker/signals.notify_items` and traced the issue down `active_knocks` always returns false as `_thread_locals` never has a `knock_enabled` attr. set. If I set this attr manually before the call to `active_knocks` the signal fires normally (and everything works as expected).

Is there something I'm missing running this locally? 

(Calling `send_knock()` manually on the model through the django shell fires the knock successfully also)

I've added some detail below. If you need any more information please let me know. Thanks again!

__Local Setup__:

Running the following commands to start the local environment:

```
# start redis instance
redis-server 

# start django instance (per channel docs)
./manage.py runserver 0.0.0.0:80 --noworker

# start django/channel worker (per channel docs)
./manage.py runworker -v 2
```

Local Docker container installed with the following:

- python 3.5.2
- django 1.8.17
- djangocms 3.4
- djangocms-blog (stable)
- asgi_redis (stable)
- knocker (stable)
- channels (stable)
- redis (stable, installed on the same box as django)

```python
# settings.base.py
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
        "ROUTING": "apps.blog.routing.channel_routing",
    },
}
```

```python
# routing.py
from channels import include
from knocker.routing import channel_routing as knocker_routing

channel_routing = [
    include(knocker_routing, path=r'^/knocker'),
]
```

```html
<!-- base.html knocker scripts (per docs) -->
{% addtoblock "js" %}<script src="{% static "js/knocker.js" %}"></script>{% endaddtoblock %}
{% addtoblock "js" %}<script src="{% static "js/reconnecting-websocket.min.js" %}"></script>{% endaddtoblock %}
{% addtoblock "js" %}
<script type="text/javascript">
    // TODO: Move this, and possibly other knocker code, into webpack
    var knocker_language = "{{ LANGUAGE_CODE }}";
    var knocker_url = "/knocker";
</script>
{% endaddtoblock %}
```

__Hardware:__

```text
OSX El Capitan (10.11.16)
2.6GHz Intel, 16GB Ram
```

**Comment by aubricus** [comment]
Closing since it's been 21 days with no response.

**Comment by yakky** [comment]
Sorry @aubricus apparently I lost the notification of this issue.
I think I identified the issue, I'm reopening a posting a possible solution soon
